### ISSUE TITLE
GET and POST methods?

### ISSUE THREAD

**Issue by pangoro24** [hugokernel/micropython-nanoweb#1]
How to use GET method with parameters and POST method?
Any example to implement http methods?

**Comment by hugokernel** [comment]
You can do that by accessing request method attribute.

```
async def only_get_method(request):
    if request.method != "GET":
        raise HttpError(request, 501, "Not Implemented")
```

**Comment by pangoro24** [comment]
Can you provide a demo using GET and POST? That will be helpful

**Comment by hugokernel** [comment]
Sorry for the late reply.

I will add more examples when I have time.
