### ISSUE TITLE
Energy efficiency

### ISSUE THREAD

**Issue by ser** [hugokernel/micropython-nanoweb#15]
I deployed plain nanoweb on a micro-controller and I'm observing it takes a lot of power while being idle, it continuously varies from 5 to 20 mA. How to make it more energy efficient?

**Comment by hugokernel** [comment]
I think the problem is Micropython / uasyncio related and we can't do anything about that in Nanoweb code.

**Comment by ser** [comment]
You are correct, unfortunately - it's indeed python itself and related wifi driver... Thanks, I'm closing the issue.
