### ISSUE TITLE
Expending the request handler (Feature request)

### ISSUE THREAD

**Issue by riffnshred** [hugokernel/micropython-nanoweb#16]
Im currently working on a project where I run a wifi manager and allow the user to setup wifi through and access point. All good so far until I try to read the credentials from the POST request, I see that in the ` async def handle(self, reader, writer):` that the only data that is handled from the reader is the `method` and the `url`. 

I started working on expending that function to read the full request into a bytearray and handle more data. Would you be interested to add it in if I send a PR ? I dont mean to go super in dept and handle advanced http stuff (Im no HTTP expert anyway). 

Thank you so much for creating and maintaining this project, I tried all of them out there and they are either too expensive memorywise or not up to date with the latest asyncio

cheers

**Comment by hugokernel** [comment]
No more activity.
