### ISSUE TITLE
POST method implementation issues

### ISSUE THREAD

**Issue by krishnak** [hugokernel/micropython-nanoweb#21]
Hi this is more of a query than an issue with your code

In your nanoweb.py code you have
```

async def handle(self, reader, writer):
        items = await reader.readline()
        items = items.decode('ascii').split()
        if len(items) != 3:
            return

        request = Request()
        request.read = reader.read
        request.write = writer.awrite
        request.close = writer.aclose
```

When I make request from two different clients. I expect the request object to be empty whenever a new request arrives. However I am able to access the request.header of the first client when I am processing the request of the second client.

I am not new to programming or OO, only new to python. So I am making an assertion based on wisdom than my python syntax, that the Request class should be like 
```

class Request:
    def __init__(self):
        self.url = ""
        self.method = ""
        self.headers = {}
        self.route = ""
        self.read = None
        self.write = None
        self.close = None
```

I am setting a Cookie in one client, however when the second client makes a request it doesn't send a cookie because it is hitting the server for the first time, however when I do a request.header - it has the cookie of the other client.

Only with the above change, the request object doesn't get shared across multiple clients.

Please feel free to share your thoughts

**Comment by hugokernel** [comment]
Hi, It makes sense, I'll see to patch this quickly.
Thanks for the feedback.
