### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by soulraven** [hugokernel/micropython-nanoweb#22]
hi,
i am trying to use you lib, but i get some strange behavior, because when i try to extend the Nanoweb class i get memory allocation error. Also when i try to import the class i get the same error.
i am using: MicroPython v1.20.0 on 2023-04-26; ESP module with ESP8266

anyone have encountered this problem?

**Comment by puhitaku** [comment]
It's not that strange because ESP8266 has small writing memory. Bisecting the addition of lines and sharing the entire code (your extended Nanoweb and the main.py) with minimal additions that causes the error is necessary to find what's wrong.

**Comment by soulraven** [comment]
hello.
 
main.py: https://pastebin.com/GaSQhByM
web_server.py: https://pastebin.com/waAYjSzf

**Comment by puhitaku** [comment]
The `WebServer` class extends `Nanoweb` from this repository, which means the original nenoweb is innocent about the problem, I think.

> i have also try only to import the Nanoweb class directly from REPL and i get the same error, "memory allocation failed".

Your `lib` module has other stuff that might cause implicit side effects like additional memory allocation. Please erase all things in the ESP8266 and try importing the unmodified nanoweb.py solely.

**Comment by soulraven** [comment]
hi,
i manage to found the problem inside another file, something is not working right on that file.
Now i am trying to make the nanoweb to work with captive portal in AP mode and regular web server in STA mode.

**Comment by puhitaku** [comment]
Good to hear that you find the root cause. I think this topic is now set and ready to close @soulraven
