### ISSUE TITLE
Connection Reset error when responding to request after reading part of request

### ISSUE THREAD

**Issue by kestrel-x86** [hugokernel/micropython-nanoweb#25]
On an ESP8266 with Micropython 1.22 and the latest NanoWeb as of this submission.

Consider this endpoint

```py
@Server.route("/test")
async def test(request):
    if request.method != "POST":
        await request.write(
            f"HTTP/1.0 405 Method Not Allowed\r\n\r\nMethod Not Allowed"
        )
        return

    header = await request.read(4)

    if header == b"abcd":
        print("200")
        await request.write(f"HTTP/1.0 200 OK\r\n\r\nOK")
    else:
        print("415")
        await request.write(
            f"HTTP/1.0 415 Unsupported Media Type\r\n\r\nUnsupported Media Type"
        )
```
A file would be uploaded, but before accepting all of the contents the first four bytes would be read as the file header. When put into use in the real world this would continue reading chunks of the uploaded file until it is consumed, then responding to the request, but for now it just returns a pass/fail type of response.

When uploading 4 correct bytes it works as expected:

```sh
$ curl -X POST -d "abcd" 192.168.1.133/test
OK
```

When uploading four incorrect bytes, or fewer than four, it works as expected:

```sh
$ curl -X POST -d "wxyz" 192.168.1.133/test
Unsupported Media Type

$ curl -X POST -d "abc" 192.168.1.133/test
Unsupported Media Type
```

However, when submitting more than four bytes, leaving the stream partially read, the error occurs:

```sh
$ curl -X POST -d "abcdwxyz" 192.168.1.133/test
curl: (56) Recv failure: Connection was reset
```

Any value in the payload that is larger than 4 bytes will cause this error. It seems like unread data is a problem. If I read all of the bytes (eg by lazily adding a `_ = await response.read(4)` after the first read then sending 8 bytes) and discard them the response passes normally, but that of course defeats part of the reason I want to read the file header before continuing.

**Comment by hugokernel** [comment]
There is no problem here: The server close the connection before reading all the client stream.
