### ISSUE TITLE
example.py missing base64_decode() reference

### ISSUE THREAD

**Issue by JennaSys** [hugokernel/micropython-nanoweb#5]
I'm running this on an ESP8266 and the _example.py_ module seems to be missing a reference to the `base64_decode()` function.  Is there a missing import in the module or does it use a different uPy port?  I defined the function myself and it seemed to be working after that:

```
import ubinascii

def base64_decode(val):
    return ubinascii.a2b_base64(val)
```

**Comment by hugokernel** [comment]
Hi,

I will update the example with this import:

```python
from ubinascii import a2b_base64 as base64_decode
```

Thank you.
