### ISSUE TITLE
send_response() not implemented in example.py

### ISSUE THREAD

**Issue by JennaSys** [hugokernel/micropython-nanoweb#6]
In the _example.py_ module, `api_upload()` and `api_delete()` functions both call a function `send_response()` that is not defined.

**Comment by JennaSys** [comment]
Something like this allows the example to work, but I'm not sure if you intended this function to be part of _nanoweb.py_ like the `send_file() `function is.

```
async def send_response(request, http_code=200, response='OK'):
    await request.write("HTTP/1.1 {0} {1}\r\n\r\n".format(http_code, response))
```

**Comment by hugokernel** [comment]
Hi John,

The `send_response` function is:

```python
async def send_response(request, code=200, message="OK"):
    await request.write("HTTP/1.1 %i %s\r\n" % (code, message))
    await request.write("Content-Type: application/json\r\n\r\n")
    await request.write('{"status": true}')
```

I will add it in the example.
Thank you.
