### ISSUE TITLE
Add configurable static file folder

### ISSUE THREAD

**Issue by JennaSys** [hugokernel/micropython-nanoweb#7]
I know you want to keep nanoweb as small as possible, but would it be possible to add a property for specifying the location of static files besides having it only look in the current folder?

Or, for example, is there a way to reroute static files so that `/*` reroutes to `/sd/static/*`?

**Comment by JennaSys** [comment]
I did kind of work around it by re-writing the url using the `callback_request` property in my app and filtering out api calls and the default route:

```
def static_rewrite(request):
    if not request.url.startswith('/api/') and len(request.url) > 1:
        request.url = STATIC_DIR + request.url[1:]

naw.callback_request = static_rewrite
```
I have a specific route for '/' so I can rewrite the url for _index.html_ there.

Is there another solution or is that actually what the `callback_request` property is intended for?

**Comment by hugokernel** [comment]
Hi John, currently, it is the only and cleaner way to to this.

I'm thinking of adding a constant and an argument to the Nanoweb class that would specify a folder for all static files.

**Comment by JennaSys** [comment]
That would work.  In addition to the above, I'm already setting the location of the default route using the INDEX_FILE "constant":
`naw.INDEX_FILE = STATIC_DIR + 'index.html'`

On a side note, I've been using nanoweb on an ESP-01 with an attached SD card and really pushing the limits of sensibility, haha.  This has been a fun library to play around with so I hope you don't mind my comments :)

**Comment by hugokernel** [comment]
Hey, ok, I think that adding the constant will be enough.

> On a side note, I've been using nanoweb on an ESP-01 with an attached SD card and really pushing the limits of sensibility, haha. This has been a fun library to play around with so I hope you don't mind my comments :)

Not at all, now I just want to see a picture of the setup ! ;)

**Comment by JennaSys** [comment]
Awesome! Most of the issues I've run in to so far I've just been handling inside my app. and have tried to avoid making modifications to nanoweb itself.  But I'll open separate GH issues for some of those just to document what I've run into and you can do with them as you wish.

I'll definitely be doing a writeup on my little experiment and let you know when I post it.  It's crazy stuff lol.
