### ISSUE TITLE
Possible updates for send_file() function

### ISSUE THREAD

**Issue by JennaSys** [hugokernel/micropython-nanoweb#8]
I made a few additions to the `send_file()` function in my local copy of _nanoweb.py_ for your consideration (but feel free to close and ignore):
1. Added content-type header
2. Added content-length header
3. Changed to a reusable bytearray buffer for the file read loop to be more predictable with memory usage

I also increased the read chunk size 8-fold to speed up the transfer on larger files, but that's more subjective.  Maybe make that chunk size user configurable?

I've thrown some image files and large JavaScript files (React bundle) at it, and while not fast, it seems reasonably reliable for what it is.  Here's the end result of what I've been using:
```
content_types = dict(
    html='text/html',
    css='text/css',
    js='application/javascript',
    json='application/json',
    jpg='image/jpeg',
    ico='image/x-icon',
    default='text/plain',
    )

async def send_file(request, filename):
    content_type = content_types.get(filename.split('.')[-1], content_types['default'])
    file_size = os.stat(filename)[6]

    await request.write("HTTP/1.1 200 OK\r\n")
    await request.write("Content-Type: {}\r\n".format(content_type))
    await request.write("Content-Length: {}\r\n\r\n".format(file_size))

    buf = bytearray(512)
    try:
        with open(filename, "r") as f:
            while True:
                bytes = f.readinto(buf)
                if bytes == 0:
                    break
                await request.write(buf[:bytes])
    except OSError as e:
        if e.args[0] != uerrno.ENOENT:
            raise
        raise HttpError(request, 404, "File Not Found")
    finally:
        del buf
        gc.collect()
```

**Comment by hugokernel** [comment]
Hi,
Thanks for the suggestion, however, it's useful but not completely indispensable and I'm afraid it will make the memory footprint too big.

**Comment by hugokernel** [comment]
No more activity.
