### ISSUE TITLE
How to upload ?

### ISSUE THREAD

**Issue by imediabank** [hugokernel/micropython-nanoweb#9]
i'm new bit, Download file is perfect, but how to upload file to ESP32 , How can I send PUT Method from example.html ?

**Comment by imediabank** [comment]
Thanks I will try it today

**Comment by imediabank** [comment]
Not Implemented

that's the result after submit
i tried to put method="POST" or method="PUT"

still doesn't work ! PLease help

**Comment by imediabank** [comment]
It work but i have to change 
<form method="POST" action="/api/upload/" enctype="multipart/form-data" >
				File:
				<input type="file" name="file" id="file" > <br/>
				<input type="submit" value="Upload">
			</form>

and 

    if request.method != "POST":
        raise HttpError(request, 501, "Not Implemented")

but next question is when I upload a png file, the header will shows me

------WebKitFormBoundaryGRTBqwRvwP3kYgQ2
Content-Disposition: form-data; name="file"; filename="javalogo.png"
Content-Type: image/png

NG
ajshxj ahsx a
------WebKitFormBoundaryGRTBqwRvwP3kYgQ2

How can I remove all text header ?

**Comment by hugokernel** [comment]
Could you try with the new updated example please ?
